const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const base = process.env.SPORTLINE_TEST_URL || 'http://127.0.0.1:8765';
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.addInitScript(() => { window.open = url => { window.testUrl = url; }; });
    await page.goto(base + '/concept/?svc=string&src=academy-demo&shop=5th');
    assert.match(await page.locator('#referral').innerText(), /academy-demo/);
    assert.equal(await page.locator('#total').innerText(), '₹550');
    await page.locator('#brand').selectOption('Victor');
    await page.locator('#string').selectOption('1');
    assert.equal(await page.locator('#colour').inputValue(), 'Pink');
    assert.equal(await page.locator('#total').innerText(), '₹850');
    await page.locator('#advanced summary').click();
    await page.locator('#knots').check();
    await page.locator('#pre').check();
    assert.equal(await page.locator('#total').innerText(), '₹900');
    await page.locator('#tension').fill('36');
    await page.locator('#next').click();
    assert.match(await page.locator('#error').innerText(), /18 and 35/);
    await page.locator('#tension').fill('25');
    await page.locator('#next').click();
    await page.locator('#next').click();
    assert.match(await page.locator('#error').innerText(), /name/);
    await page.locator('#name').fill('Test Player');
    await page.locator('#phone').fill('+91 98765 43210');
    await page.locator('#gear').fill('Test racket');
    await page.locator('#notes').fill('<b>Handle with care</b>');
    await page.locator('#priority').check();
    assert.equal(await page.locator('#total').innerText(), '₹1,000');
    await page.locator('#next').click();
    const review = await page.locator('#review-details').innerText();
    for (const value of ['VBS 68 Power', '25 lbs', '5th Avenue', 'Test Player', 'academy-demo', '₹1,000']) assert(review.includes(value), value);
    assert.equal(await page.locator('#review-details dd b').count(), 0);
    await page.locator('#next').click();
    const url = new URL(await page.evaluate(() => window.testUrl));
    assert.equal(url.pathname, '/918056436668');
    const msg = url.searchParams.get('text');
    for (const value of ['VBS 68 Power', '5th Avenue', '9876543210', 'academy-demo', '₹1,000']) assert(msg.includes(value), value);
    assert(await page.locator('#sent').isVisible());
    // Switching the service must not carry racket extras or urgency into bat pricing.
    await page.locator('[data-step="0"]').click();
    await page.locator('[data-sport="cricket"]').click();
    await page.locator('#next').click();
    assert.match(await page.locator('#error').innerText(), /at least one/);
    await page.locator('input[value="hand"]').check();
    await page.locator('input[value="machine"]').check();
    assert(!(await page.locator('input[value="hand"]').isChecked()));
    await page.locator('input[value="crack"]').check();
    assert.equal(await page.locator('#total').innerText(), '₹800 + quote');
    await page.locator('#handle').selectOption('750');
    assert.equal(await page.locator('#total').innerText(), '₹1,550 + quote');
    await page.locator('#next').click();
    assert(!(await page.locator('#timing-fields').isVisible()));
    await page.locator('#next').click();
    await page.locator('#next').click();
    const bat = new URL(await page.evaluate(() => window.testUrl)).searchParams.get('text');
    assert(!bat.includes('Priority'));
    assert(bat.includes('Crack binding: quote after inspection'));
    assert(bat.includes('Finish date confirmed after inspection'));
    await page.goto(base + '/concept/?sport=cri&src=%3Cimg%20src=x%3E');
    assert(await page.locator('#cricket-fields').isVisible());
    assert.equal(await page.locator('#referral img').count(), 0);
    for (const width of [360, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Overflow at ' + width);
    }
    assert.deepEqual(errors, []);
    console.log('PASS: badminton/cricket flows, QR aliases and shop/source, matching colours, estimate maths, exclusive knocking methods, validation, safe review rendering, WhatsApp handoff, and 360–1440px layouts. No messages sent.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
